# Generated by Django 3.2.4 on 2022-04-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_scrap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_scrap',
            new_name='Product',
        ),
    ]
